version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
     - "80:80"
     - "443:443"
    restart: always
    volumes:
     - ./conf.d:/etc/nginx/conf.d
     - ./content/:/usr/share/nginx/html
    links:
      - php

  php:
    image: php:fpm-stretch
    container_name: php
    volumes:
     - ./content/:/var/www/html